### PR TITLE
Expand TIR -- Simple statements.

### PR DESCRIPTION
**Pull request by vext01**
These are the bits needed for https://github.com/softdevteam/ykrustc/pull/10.

See commit messages for more.

### CODE REVIEW

**Comment by ltratt** [comment]
It looks like this needs nightly, hence why the stable build is failing?

**Comment by vext01** [comment]
It's just a difference between rustfmt in nightly and stable (whitespace).

**Comment by ltratt** [comment]
Aha! OK, if/when the tests pass, please squash.

**Comment by vext01** [comment]
Splat.

**Pull request merged**
